/** Auto-generated by scripts/sync-dist.mjs from dist/ — do not edit. */

const VALID = new Set<string>([
  "/",
  "/404.html",
  "/about",
  "/about/",
  "/blog",
  "/blog/",
  "/blog/garage-door-repair-cost-palm-beach",
  "/blog/garage-door-repair-cost-palm-beach/",
  "/contact",
  "/contact/",
  "/css/input.css",
  "/css/style.css",
  "/faq",
  "/faq/",
  "/images/IMG_0430.png",
  "/images/IMG_0430.webp",
  "/images/IMG_4765.png",
  "/images/IMG_4765.webp",
  "/images/IMG_6884.png",
  "/images/IMG_6884.webp",
  "/images/PHOTO-2026-04-03-16-13-08.png",
  "/images/PHOTO-2026-04-03-16-13-09.png",
  "/images/PHOTO-2026-04-03-16-13-09.webp",
  "/images/PHOTO-2026-04-03-16-13-09__1_.png",
  "/images/PHOTO-2026-04-03-16-13-09__1_.webp",
  "/images/logo-schema-300x60.png",
  "/images/logo.png",
  "/images/palm-beach-garage-door-repair-dandb.webp",
  "/index.html",
  "/js/main.js",
  "/llms.txt",
  "/locations/boca-raton",
  "/locations/boca-raton/",
  "/locations/boynton-beach",
  "/locations/boynton-beach/",
  "/locations/delray-beach",
  "/locations/delray-beach/",
  "/locations/jupiter",
  "/locations/jupiter/",
  "/locations/lake-worth",
  "/locations/lake-worth/",
  "/locations/palm-beach-gardens",
  "/locations/palm-beach-gardens/",
  "/locations/wellington",
  "/locations/wellington/",
  "/locations/west-palm-beach",
  "/locations/west-palm-beach/",
  "/privacy",
  "/privacy/",
  "/robots.txt",
  "/services/emergency-garage-door-repair",
  "/services/emergency-garage-door-repair/",
  "/services/garage-door-cable-repair",
  "/services/garage-door-cable-repair/",
  "/services/garage-door-installation",
  "/services/garage-door-installation/",
  "/services/garage-door-opener-repair",
  "/services/garage-door-opener-repair/",
  "/services/garage-door-replacement",
  "/services/garage-door-replacement/",
  "/services/garage-door-spring-repair",
  "/services/garage-door-spring-repair/",
  "/services/garage-door-tune-up",
  "/services/garage-door-tune-up/",
  "/sitemap-images.xml",
  "/sitemap.xml"
]);

export function isValidPathname(pathname: string): boolean {
  if (VALID.has(pathname)) return true;
  try {
    const decoded = decodeURIComponent(pathname);
    if (decoded !== pathname && VALID.has(decoded)) return true;
  } catch {
    /* ignore malformed escapes */
  }
  return false;
}
