import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const root = path.join(__dirname, "..");
const dist = path.join(root, "dist");
const functionsDir = path.join(root, "functions");

const copyFiles = [
  "index.html",
  "404.html",
  "robots.txt",
  "sitemap.xml",
  "sitemap-images.xml",
  "llms.txt",
  "_routes.json",
  "_redirects",
];
const copyDirs = ["blog", "css", "js", "locations", "services", "about", "contact", "faq", "privacy", "assets"];

if (fs.existsSync(dist)) fs.rmSync(dist, { recursive: true, force: true });
fs.mkdirSync(dist, { recursive: true });

for (const f of copyFiles) {
  const src = path.join(root, f);
  if (fs.existsSync(src)) fs.copyFileSync(src, path.join(dist, f));
}
for (const d of copyDirs) {
  const src = path.join(root, d);
  if (fs.existsSync(src)) fs.cpSync(src, path.join(dist, d), { recursive: true });
}

const images = path.join(root, "images");
if (fs.existsSync(images)) fs.cpSync(images, path.join(dist, "images"), { recursive: true });

/** @param {string} distDir */
function collectValidPathnames(distDir) {
  const paths = new Set();

  /** @param {string} relPosix */
  function walk(relPosix) {
    const readDir = relPosix === "." ? distDir : path.join(distDir, relPosix.split("/").join(path.sep));
    if (!fs.existsSync(readDir)) return;
    for (const ent of fs.readdirSync(readDir, { withFileTypes: true })) {
      const childRel = relPosix === "." ? ent.name : `${relPosix}/${ent.name}`;
      const posix = childRel.replace(/\\/g, "/");
      if (ent.isDirectory()) {
        walk(posix);
      } else if (posix === "index.html") {
        paths.add("/");
        paths.add("/index.html");
      } else if (posix.endsWith("/index.html")) {
        const dir = posix.slice(0, -"/index.html".length);
        const base = "/" + dir;
        paths.add(base);
        paths.add(base + "/");
      } else {
        if (posix.endsWith(".gitkeep") || posix.split("/").some((seg) => seg.startsWith("_"))) {
          continue;
        }
        paths.add("/" + posix);
      }
    }
  }

  walk(".");
  return Array.from(paths).sort();
}

const pathnames = collectValidPathnames(dist);
const pathLines = pathnames.map((p) => `  ${JSON.stringify(p)}`).join(",\n");
const validPathsTs = `/** Auto-generated by scripts/sync-dist.mjs from dist/ — do not edit. */

const VALID = new Set<string>([
${pathLines}
]);

export function isValidPathname(pathname: string): boolean {
  if (VALID.has(pathname)) return true;
  try {
    const decoded = decodeURIComponent(pathname);
    if (decoded !== pathname && VALID.has(decoded)) return true;
  } catch {
    /* ignore malformed escapes */
  }
  return false;
}
`;
fs.mkdirSync(functionsDir, { recursive: true });
fs.writeFileSync(path.join(functionsDir, "_valid-paths.ts"), validPathsTs, "utf8");

const notFoundSrc = path.join(root, "404.html");
const notFoundHtml = fs.readFileSync(notFoundSrc, "utf8");
const notFoundTs = `/** Auto-generated from 404.html by scripts/sync-dist.mjs — do not edit. */

export const NOT_FOUND_HTML: string = ${JSON.stringify(notFoundHtml)};
`;
fs.writeFileSync(path.join(functionsDir, "_404-html.ts"), notFoundTs, "utf8");

console.log("Synced static assets to dist/");
console.log(`Wrote functions/_valid-paths.ts (${pathnames.length} pathnames)`);
console.log("Wrote functions/_404-html.ts");
